name: Run script on EC2

on:
  pull_request:
    branches: 
      - dev
    types: [closed]
  push:
    branches:
      - dev

jobs:
  deploy_on_main:
    if: ${{ github.ref == 'refs/heads/dev' && github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI      
        run: |
          echo ${{ github.ref }}
          echo $GITHUB_REF
          echo ${{ github.event_name }}
          echo $GITHUB_EVENT_NAME

