name: Run script on EC2

on:
  pull_request:
    branches: 
      - main
      - dev
    types: [closed]
  push:
    branches:
      - main
      - dev

jobs:
  deploy_on_push_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI      
        run: |
          echo 'push event'
          echo ${{ github.event_name }}
          echo $GITHUB_EVENT_NAME

  deploy_on_pr_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          echo 'pr event'
          echo ${{ github.ref }}
          echo $GITHUB_REF

